from turtle import Turtle, done, TurtleGraphicsError

try:
        flags = Turtle()
        flags.pensize(5)
        flags.speed(3)
        flags.color("#054187")

        def draw(x, y):
                flags.penup()
                flags.goto(x, y)
                flags.pendown()
        for intentation in range(24):
                flags.forward(80)
                flags.backward(80)
                flags.left(15)
        draw(0, -80)
        flags.circle(80, 360)
        flags.color("green")
        flags.begin_fill()
        flags.backward(350)
        flags.right(90)
        flags.forward(200)
        flags.left(90)
        flags.forward(700)
        flags.left(90)
        flags.forward(200)
        flags.left(90)
        flags.end_fill()
        flags.color("orange")
        draw(-350, 80)
        flags.begin_fill()
        flags.right(180)
        flags.forward(700)
        flags.left(90)
        flags.forward(200)
        flags.left(90)
        flags.forward(700)
        flags.left(90)
        flags.end_fill()
        done()
except TurtleGraphicsError:
        print("")